# Configurations
title:            Zero Cyber Exercise
longtitle:        ""
author:           ardiesan
email:            ardieolavides@gmail.com
description: >
 Basics of Cyber Security 

version:          1.0
gitbook_version:  3.2.3

url:              'https://ardiesan.github.io'
baseurl:          '/zero'
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: ardiesan/jekyll-gitbook

toc:
  in_menu: false
  in_post: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: gruvbox

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:categories/:title:output_ext

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
